.Dd February 16, 2019
.Dt ARCHMAILBOX 7
.Os
.Sh NAME
.Nm archmailbox
.Nd archmailbox project
.Sh DESCRIPTION
The
.Nm
provides a number of different programs and
configurations to allow for easy mail server setup.
This manual page documents the programs and the
configuration that is used by default.
.Sh BASIC LAYOUT
.Nm
uses
.Xr smtpd 8
for mail delivery and receipt.
Incoming mail is filtered using
.Xr rspamd 8
using the
.Xr rspamc 1
command before being delivered to
.Xr dovecot 1
for delivery to the local mail store.
Outgoing mail is received by
.Xr smtpd 8
which then forwards the mail to
.Cm pyrelay-rspamd
which uses
.Xr rspamd 8
to DKIM sign the messages.
.Cm pyrelay-rspamd
Then sends the messages back to
.Xr smtpd 8
on a trusted port which then relays the mail to the destination mail server.
.Pp
Mail is stored locally in the maildir format compressed using
.Xr xz 1
compression.
It is subject to a quota default quota of 15GB per user and an
message size limit of 100MB.
.Pp
Mail users are virtual and are stored in the
.Pa /etc/smtpd/smtp.sqlite
database.
The passwords are hashed using the Argon2 password hashing scheme.
.Pp
acme.sh is used to generate and renew Let's Encrypt tls
certificates.
The configuration files are set up under
.Pa /var/lib/acme
and the installed certificates used by the server are located in
.Pa /etc/acme
.Pp
The
.Cm gencert
command will use stand-alone mode using alpn.
This means that no other service can be listening on port 443 of the server.
If you already have a web server set up, acme.sh can be used to issue
the certificate and installed using
.Cm deploycert .
.Sh COMMANDS
.Nm
comes with a number of scripts to ease administration of the
server.
.Bl -tag -width indent
.It Xr archmailbox-install 8
used to install the packages and initial configuration files
.It Xr mailboxctl 8
used to manage the configuration, as well as backup and restore
the server.
.It Xr manage-mail-users 8
used to manage the SQLite user database.
.El
.Sh SECURITY
.Nm
attempts to be secure by default.
.Xr dovecot 1
will deliver new mail using the
.Li vmail
user.
This user is also given access to communicate with
.Xr rspamd 8
via unix domain socket.
The
.Xr dovecot 1
authentication process uses the smtpd group to allow access to the
user configuration database.
.Pp
The email data is protected at rest using trees.
trees will encrypt email delivered using public-key cryptography.
The private part of the key is stored in the user database encrypted
using a symmetric key generated with argon2 and a salt separate than
the one used to verify the password.
.Pp
The
.Xr treesutil 1
utility can be used to manage trees user data and can also be used
to decrypt a trees encrypted file.
.Pp
The _rspamd user has control over DKIM keys stored in
.Pa /var/lib/rspamd/dkim .
No other user is given access to the keys.
.Pp
The ports used for dkim signing are protected against malicious
users with a simple nftables based rule set.
It uses the table dkim_filter for both ip and ip6.
.Pp
The default nftables service included with the nftables package
deletes all rules and then replaces them with the rules in
.Pa /etc/nftables.conf .
If this service is being used add an include of
.Pa /etc/archmailbox-nftables.conf
in this file and disable the archmailbox\&-\&nftables service.
.Sh SEE ALSO
.Xr dovecot 1 ,
.Xr treesutil 1 ,
.Xr archmailbox-install 8 ,
.Xr mailboxctl 8 ,
.Xr manage-mail-users 8 ,
.Xr nft 8 ,
.Xr rspamd 8 ,
.Xr smtpd 8
.Pp
.Lk https://0xacab.org/riseuplabs/trees trees
